version: '2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: StrongPassw0rd
      MSSQL_PID: Developer
    ports:
      - '1433:1433'
    volumes:
      - ms-sqlserver-data:/var/opt/mssql
  app:
    build:
      context: .
      dockerfile: 'dockerfile_dev'
    depends_on:
      - sqlserver
    environment:
      RAILS_ENV: development
      OSS_BUCKET_NAME: $OSS_BUCKET_NAME
      OSS_IMAGE_BUCKET_NAME: $OSS_IMAGE_BUCKET_NAME
      OSS_USE_S3_STATIC_HOSTING: $OSS_USE_S3_STATIC_HOSTING
      OSS_REGION: $OSS_REGION
      OSS_CDN_BASE_URL: $OSS_CDN_BASE_URL
      OSS_SQS_URL: $OSS_SQS_URL
      OSS_AWS_ACCESS_ID: $OSS_AWS_ACCESS_ID
      OSS_AWS_SECRET_KEY: $OSS_AWS_SECRET_KEY
      OSS_DB_ENGINE_DEV: sqlserver
      OSS_DB_PORT_DEV: 1433
      OSS_DB_NAME_DEV: slidehub
      OSS_DB_USERNAME_DEV: sa
      OSS_DB_PASSWORD_DEV: StrongPassw0rd
      OSS_DB_URL_DEV: sqlserver
      OSS_DB_USE_AZURE_DEV: 'false'
      OSS_DB_ENGINE_TEST: sqlserver
      OSS_DB_PORT_TEST: 1433
      OSS_DB_NAME_TEST: test_slidehub
      OSS_DB_USERNAME_TEST: sa
      OSS_DB_PASSWORD_TEST: StrongPassw0rd
      OSS_DB_URL_TEST: sqlserver
      OSS_DB_USE_AZURE_TEST: 'false'
      OSS_FACEBOOK_APP_ID: $OSS_FACEBOOK_APP_ID
      OSS_FACEBOOK_APP_SECRET: $OSS_FACEBOOK_APP_SECRET
      OSS_TWITTER_CONSUMER_KEY: $OSS_TWITTER_CONSUMER_KEY
      OSS_TWITTER_CONSUMER_SECRET: $OSS_TWITTER_CONSUMER_SECRET
      OSS_FROM_EMAIL: test@example.com
      OSS_SMTP_SERVER: localhost
      OSS_SMTP_PORT: 1025
      OSS_SMTP_AUTH_METHOD: plain
      OSS_SMTP_PASSWORD: test
      OSS_SMTP_USERNAME: test
      RAILS_LOG_TO_STDOUT: 'yes'
    ports:
      - '3000:3000'
      - '1080:1080'
    volumes:
      - .:/opt/application/current:cached

volumes:
  ms-sqlserver-data:
    driver: local
